FROM ubuntu:22.04
RUN apt-get update -y && apt-get install -y python3 python3-pip && apt-get install -y mysql-server
COPY ./requirements.txt /app/requirements.txt
WORKDIR /app
RUN pip3 install -r requirements.txt
COPY . /app
CMD service mysql start ; mysql --execute="ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY '';" ; mysql --execute="create database events;" ; python3 create_tables.py ; python3 app.py